import flImage from "./src/assets/images/fl-image.png";
import fieldsImg from "./src/assets/images/fieldsImage.png";

export const plotsListData = [
  {
    id: "FL-001",
    state_name: "Hessen",
    zipcode: 60306,
    municipality_name: "Frankfurt",
    district_name: "Westend",
    cadastral_area: "Field 12",
    cadastral_parcel: "Parcel 34",
    land_use: "Residential Land",
    plot_number_main: 10000,
    plot_number_secondary: "123-456-789",
    image: flImage,
    analyzePlus: "active",
  },
  {
    id: "FL-002",
    state_name: "Bayern",
    zipcode: 80331,
    municipality_name: "Munich",
    district_name: "Altstadt",
    cadastral_area: "Field 15",
    cadastral_parcel: "Parcel 56",
    land_use: "Commercial Land",
    plot_number_main: 15000,
    plot_number_secondary: "987-654-321",
    image: flImage,
    analyzePlus: "inactive",
  },
  {
    id: "FL-003",
    state_name: "Baden-Württemberg",
    zipcode: 70173,
    municipality_name: "Stuttgart",
    district_name: "Mitte",
    cadastral_area: "Field 20",
    cadastral_parcel: "Parcel 78",
    land_use: "Agricultural Land",
    plot_number_main: 20000,
    plot_number_secondary: "456-789-123",
    image: flImage,
    analyzePlus: "active",
  },
];

export const flurstuckData = {
  id: "FL-001",
  state_name: "Hessen",
  zipcode: 60306,
  municipality_name: "Frankfurt",
  district_name: "Westend",
  cadastral_area: "Field 12",
  cadastral_parcel: "Parcel 34",
  land_use: "Residential Land",
  plot_number_main: 10000,
  plot_number_secondary: "123-456-789",
  image: flImage,
  analyzePlus: "active",
};

export const offerItemData = {
  id: "FL-001",
  state_name: "Hessen",
  zipcode: 60306,
  municipality_name: "Frankfurt",
  district_name: "Westend",
  cadastral_area: "Field 12",
  cadastral_parcel: "Parcel 34",
  land_use: "Residential Land",
  plot_number_main: 10000,
  image: flImage,
};

export const analysePlusCartData = [
  {
    id: "FL-56141",
    state_name: "Hessen",
    zipcode: 65366,
    municipality_name: "Rüdesheim",
    district_name: "Hasensprung",
    cadastral_area: "2",
    cadastral_parcel: "35-6",
    land_use: "Grünland",
    plot_number_main: 10000,
    plot_number_secondary: "123-456-789",
    image: flImage,
    analyzePlus: "active",
  },
  {
    id: "FL-56142",
    state_name: "Hessen",
    zipcode: 65366,
    municipality_name: "Rüdesheim",
    district_name: "Hasensprung",
    cadastral_area: "2",
    cadastral_parcel: "35-6",
    land_use: "Grünland",
    plot_number_main: 10000,
    plot_number_secondary: "123-456-789",
    image: flImage,
    analyzePlus: "active",
  },
  {
    id: "FL-56143",
    state_name: "Hessen",
    zipcode: 65366,
    municipality_name: "Rüdesheim",
    district_name: "Hasensprung",
    cadastral_area: "2",
    cadastral_parcel: "35-6",
    land_use: "Grünland",
    plot_number_main: 10000,
    plot_number_secondary: "123-456-789",
    image: flImage,
    analyzePlus: "active",
  },
];

export const thankYouMarketingData = [
  {
    id: "FL-001",
    state_name: "Hessen",
    zipcode: 60306,
    municipality_name: "Frankfurt",
    district_name: "Westend",
    cadastral_area: "Field 12",
    cadastral_parcel: "Parcel 34",
    land_use: "Residential Land",
    plot_number_main: 10000,
    plot_number_secondary: "123-456-789",
    image: flImage,
    analyzePlus: "active",
  },
];

export const detailsData = [
  {
    id: "FL-001",
    state_name: "Hessen",
    zipcode: 60306,
    municipality_name: "Frankfurt",
    district_name: "Westend",
    cadastral_area: "Field 12",
    cadastral_parcel: "Parcel 34",
    land_use: "Residential Land",
    plot_number_main: 10000,
    plot_number_secondary: "123-456-789",
    image: fieldsImg,
    analyzePlus: "inactive",
    infrastructure: "Freiflächensolar",
    evaluation: "Potentiell geeignet",
  },
];

export const myOfferData = [
  {
    id: "FL-56141",
    state_name: "Hessen",
    zipcode: 65366,
    municipality_name: "Rüdesheim",
    district_name: "Hasensprung",
    cadastral_area: "2",
    cadastral_parcel: "35-6",
    land_use: "Grünland",
    plot_number_main: 10000,
    plot_number_secondary: "123-456-789",
    image: fieldsImg,
    analyzePlus: "active",
  },
  {
    id: "FL-56142",
    state_name: "Hessen",
    zipcode: 65366,
    municipality_name: "Rüdesheim",
    district_name: "Hasensprung",
    cadastral_area: "2",
    cadastral_parcel: "35-6",
    land_use: "Grünland",
    plot_number_main: 10000,
    plot_number_secondary: "987-654-321",
    image: flImage,
    analyzePlus: "inactive",
  },
];

export const analysePlusValues = {
  items: 3,
  costPerItem: 199,
  sumOfItems: 597,
  taxPercent: 19,
  taxAmount: 113.34,
  subtotal: 711.34,
  total: 711.34,
};

export const plotSearchData = [
  {
    id: "FL-56141",
    state_name: "Hessen",
    district_name: "Rheingau-Taunus",
    land_use: "Grünland",
    plot_number_main: 10000,
    image: flImage,
    infrastructure: "Wind, Biodiversität",
    evaluation: "Potentiell geeignet",
  },
  {
    id: "FL-56142",
    state_name: "Hessen",
    district_name: "Rheingau-Taunus",
    land_use: "Grünland",
    plot_number_main: 10000,
    image: fieldsImg,
    infrastructure: "Freiflächensolar",
    evaluation: "Potentiell geeignet",
  },
];

export const myWatchlistData = [
  {
    id: "FL-56141",
    state_name: "Hessen",
    district_name: "Rheingau-Taunus",
    land_use: "Grünland",
    plot_number_main: 10000,
    image: flImage,
    infrastructure: "Freiflächensolar",
    evaluation: "Potentiell geeignet",
  },
  {
    id: "FL-56142",
    state_name: "Hessen",
    district_name: "Rheingau-Taunus",
    land_use: "Grünland",
    plot_number_main: 10000,
    image: fieldsImg,
    infrastructure: "Freiflächensolar",
    evaluation: "Potentiell geeignet",
  },
];

export const receivedMessages = [
  {
    name: "Jullu Jalal",
    message: "Our Bachelor of Commerce program is ACBSP-accredited.",
    time: "8:38 AM",
    category: "",
  },
  {
    name: "Minerva Barnett",
    message: "Get Best Advertiser In Your Side Pocket",
    time: "8:13 AM",
    category: "",
  },
  {
    name: "Peter Lewis",
    message: "Vacation Home Rental Success",
    time: "7:52 PM",
    category: "",
  },
  {
    name: "Anthony Briggs",
    message: "Free Classifieds Using Them To Promote Your Stuff Online",
    time: "7:52 PM",
    category: "",
  },
  {
    name: "Clifford Morgan",
    message: "Enhance Your Brand Potential With Giant Advertising Blimps",
    time: "4:13 PM",
    category: "",
  },
  {
    name: "Cecilia Webster",
    message: "Always Look On The Bright Side Of Life",
    time: "3:52 PM",
    category: "",
  },
  {
    name: "Harvey Manning",
    message: "Curling Irons Are As Individual As The Women Who Use Them",
    time: "2:30 PM",
    category: "",
  },
  {
    name: "Willie Blake",
    message: "Our Bachelor of Commerce program is ACBSP-accredited.",
    time: "8:38 AM",
    category: "",
  },
  {
    name: "Minerva Barnett",
    message: "Get Best Advertiser In Your Side Pocket",
    time: "8:13 AM",
    category: "Work",
  },
  {
    name: "Fanny Weaver",
    message: "Free Classifieds Using Them To Promote Your Stuff Online",
    time: "7:52 PM",
    category: "",
  },
  {
    name: "Olga Hogan",
    message: "Enhance Your Brand Potential With Giant Advertising Blimps",
    time: "4:13 PM",
    category: "Social",
  },
  {
    name: "Lora Houston",
    message: "Vacation Home Rental Success",
    time: "7:52 AM",
    category: "Friends",
  },
];

export const activeAuctionsData = [
  {
    id: "FL-56141",
    state_name: "Hessen",
    zipcode: 65366,
    municipality_name: "Rüdesheim",
    district_name: "Hasensprung",
    cadastral_area: "2",
    cadastral_parcel: "35-6",
    land_use: "Grünland",
    plot_number_main: 10000,
    plot_number_secondary: "987-654-321",
    image: flImage,
    analyzePlus: "active",
    infrastructure: "Wind, Biodiversität",
    evaluation: "Potentiell geeignet",
  },
  {
    id: "FL-56142",
    state_name: "Hessen",
    zipcode: 65366,
    municipality_name: "Rüdesheim",
    district_name: "Hasensprung",
    cadastral_area: "2",
    cadastral_parcel: "35-6",
    land_use: "Grünland",
    plot_number_main: 10000,
    plot_number_secondary: "987-654-321",
    image: fieldsImg,
    analyzePlus: "active",
    infrastructure: "Freiflächensolar",
    evaluation: "Potentiell geeignet",
  },
];

export const myAuctionsData = [
  {
    id: "FL-56141",
    state_name: "Hessen",
    zipcode: 65366,
    municipality_name: "Rüdesheim",
    district_name: "Hasensprung",
    cadastral_area: "2",
    cadastral_parcel: "35-6",
    land_use: "Grünland",
    plot_number_main: 10000,
    plot_number_secondary: "987-654-321",
    image: fieldsImg,
    analyzePlus: "active",
    infrastructure: "Freiflächensolar",
    evaluation: "Potentiell geeignet",
  },
  {
    id: "FL-56142",
    state_name: "Hessen",
    zipcode: 65366,
    municipality_name: "Rüdesheim",
    district_name: "Hasensprung",
    cadastral_area: "2",
    cadastral_parcel: "35-6",
    land_use: "Grünland",
    plot_number_main: 10000,
    plot_number_secondary: "987-654-321",
    image: fieldsImg,
    analyzePlus: "active",
    infrastructure: "Freiflächensolar",
    evaluation: "Potentiell geeignet",
  },
];

export const tenderCriteriaData = {
  list: [
    "There are many variations of passages of Lorem.",
    "There are many variations of passages of Lorem.",
    "There are many variations of passages of Lorem.",
    "There are many variations of passages of Lorem.",
    "There are many variations of passages of Lorem.",
  ],
  sonstiges:
    "There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form.",
};

export const placeABidData = {
  select1: "Option 3",
  select2: "Ja",
  select3: "Ja",
  select4: "Nein",
  select5: "Keine Angabe",
  input1: "Asdfgg",
  input2: "Fsadjdg sdfbb",
  input3: "Lfmdsm fsdmpf fasda",
  input4: "100 €",
  textArea1: "This is some random text by user....",
  textArea2: "This is sec rand text.......",
  checkbox1: true,
  checkbox2: true,
  checkbox3: true,
};

export const mockAuctionOffers = [
  {
    identifier: 'AUCTION-001',
    offer_number: 1,
    status: 'active',
    status_display: 'Active',
    hide_from_search: false,
    available_from: '2025-01-01',
    utilization: 'solar',
    utilization_display: 'Solar Energy',
    preferred_regionality: 'north',
    preferred_regionality_display: 'Northern Region',
    shareholder_model: 'shared',
    shareholder_model_display: 'Shared Ownership',
    criteria: {
      no_usage_restriction: true,
      wind_energy_restriction: false,
      solar_energy_restriction: false,
      energy_storage_restriction: false,
      eco_enhancements_restriction: true,
    },
    important_remarks: 'Important details about this auction.',
    documented_offers: [
      {
        id: 1,
        offer: 'Offer Document 1',
        uploaded_at: '2025-01-15T10:00:00Z',
        document_url: 'https://example.com/document1.pdf',
      },
    ],
    parcels: [
      {
        id: 'P12345',
        state_name: 'Bavaria',
        district_name: 'Munich',
        municipality_name: 'Munich',
        cadastral_area: 'Central',
        cadastral_parcel: 'A123',
        plot_number_main: '12',
        plot_number_secondary: '3',
        land_use: 'agriculture',
        area_square_meters: 15000,
        created_by: 'admin',
        polygon: {
          type: 'MultiPolygon',
          coordinates: [
            [
              [
                [11.57255, 48.13512],
                [11.57265, 48.13522],
                [11.57275, 48.13512],
                [11.57255, 48.13512],
              ],
            ],
          ],
        },
      },
    ],
    offer_confirmation: {
      utilization: 'LE',
      contracted_term_month: 24,
      lease_amount_yearly_lease_year_one: 1200.0,
      staggered_lease: 'YES',
      share_of_income: 'NO',
      shares_project_company: 'YES',
      message_to_landowner:
        'We are very interested in leasing your land for a solar energy project.',
      message_to_platform: 'Please prioritize our request for this region.',
      currency: 'EUR',
    },
  },
  {
    identifier: 'AUCTION-002',
    offer_number: 2,
    status: 'inactive',
    status_display: 'Inactive',
    hide_from_search: true,
    available_from: '2025-02-01',
    utilization: 'wind',
    utilization_display: 'Wind Energy',
    preferred_regionality: 'south',
    preferred_regionality_display: 'Southern Region',
    shareholder_model: 'exclusive',
    shareholder_model_display: 'Exclusive Ownership',
    criteria: {
      no_usage_restriction: false,
      wind_energy_restriction: true,
      solar_energy_restriction: true,
      energy_storage_restriction: true,
      eco_enhancements_restriction: false,
    },
    important_remarks: 'This auction requires special permissions.',
    documented_offers: [
      {
        id: 2,
        offer: 'Offer Document 2',
        uploaded_at: '2025-02-20T12:00:00Z',
        document_url: 'https://example.com/document2.pdf',
      },
    ],
    parcels: [
      {
        id: 'P67890',
        state_name: 'Baden-Württemberg',
        district_name: 'Stuttgart',
        municipality_name: 'Stuttgart',
        cadastral_area: 'West',
        cadastral_parcel: 'B456',
        plot_number_main: '45',
        plot_number_secondary: '7',
        land_use: 'residential',
        area_square_meters: 10000,
        created_by: 'user1',
        polygon: {
          type: 'MultiPolygon',
          coordinates: [
            [
              [
                [9.18293, 48.77584],
                [9.18303, 48.77594],
                [9.18313, 48.77584],
                [9.18293, 48.77584],
              ],
            ],
          ],
        },
      },
    ],
    offer_confirmation: {
      utilization: 'SA',
      sale_amount: 500000.0,
      message_to_landowner: 'We are very interested in purchasing your land.',
      message_to_platform: 'Please prioritize this offer for review.',
      currency: 'EUR',
    },
  },
];
